name = "p8f"
uuid = "ff67dfe9-30fc-464a-b6c0-49e269df59ac"
authors = ["Walter Madelim"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
